#!/bin/sh

# command description

echo "+-------------------------------------+"
echo "| Commands                            |"
echo "+-------------------------------------+"
echo "| radmindeploy : deploy radmin        |"
echo "+-------------------------------------+"