#!/bin/sh

# command description

echo "+-------------------------------------+"
echo "| Commands                            |"
echo "+-------------------------------------+"
echo "| radmin       : radmin daemon binary |"
echo "| radmindeploy : deploy radmin        |"
echo "| radminlog    : radmin log tail      |"
echo "+-------------------------------------+"