#!/bin/sh

# deploy for radmin in server - piam.me

GOPATH=/home/dhkim/funny-web

echo "[step1] copy radmin properties"
/bin/cp -rf $GOPATH/radmin.properties /data/daemons/radmin/conf

echo "[step2] copy radmin html template"
/bin/cp -rf $GOPATH/tmpl/* /data/daemons/radmin/resources/tmpl

echo "[step3] copy radmin bin"
/bin/cp -rf $GOPATH/bin/radmin ~/bin